refactor: error handling in gen_note_links

diff --git a/gen_note_links b/gen_note_links
--- a/gen_note_links
+++ b/gen_note_links
@@ -1,4 +1,4 @@
-#!/bin/env bash
+#!/usr/bin/env bash
 
 # Reads markdown files from "dir" and parses out any files with a front matter.
 # A series of href links is constructed and echoed out. The links are in the
@@ -12,10 +12,15 @@
 dir=$1
 notes=""
 
+die() {
+      echo "$1"
+      exit 2
+}
+
 if [[ -z "$dir" ]]; then
-  echo "Please specify a directory!"
-  exit 1
+  die "Please specify a directory!"
 fi
+
 
 title_re="title:\s+(.+)"
 date_re="date:\s+(.+)"
@@ -27,8 +32,7 @@ for file in "${dir}"/*.md; do
     date=""
     while read -r line; do
       if [[ $front_matter_start = false && $line != "---" ]]; then
-	echo "${file} does not have a front matter start!" >&2
-	break
+	die "${file} does not have a front matter start!"
       fi
       if [[ $line =~ $title_re ]]; then
 	title=${BASH_REMATCH[1]}
@@ -41,7 +45,7 @@ for file in "${dir}"/*.md; do
 	  notes+="<div>${date}<br><a href=\"${file/%md/html}\">${title}</a></div><br>"
 	  notes+=$'\n'
 	else
-	  echo "Could not find date and time in ${file}!" >&2
+	  die "Could not find date and time in ${file}!"
 	fi
       fi
       front_matter_start=true
